### ISSUE TITLE
Large amount of log warnings that will lead to fatal errors

### ISSUE THREAD

**Issue by rcdilorenzo** [evadne/LiveFrost#6] opened 2013-10-02 12:24 UTC
Hey, thanks for being so prompt on my last issue… Unfortunately, I've got another one.

When I hit [this line](https://github.com/ChrisXu1221/CXAlertView/blob/master/CXAlertView/CXAlertView.m#L815) in @ChrisXu1221's alert view where he is using `LFGlassView`, I get a bunch of log warnings like this:

```
<Error>: CGContextRestoreGState: invalid context 0x0. This is a serious error. This
application, or a library it uses, is using an invalid context  and is thereby contributing
to an overall degradation of system stability and reliability. This notice is a courtesy:
please fix this problem. It will become a fatal error in an upcoming update.
```

Other warnings simply substitute `CGContextRestoreGState` with other functions such as `CGContextAddRect` and `CGContextEndTransparencyLayer`. I think the root problem is an invalid context somehow.

**Comment by evadne** [comment] 2013-10-02 12:30
Which commit are you on? Which OS version? Which device?
- *

On Oct 2, 2013, at 20:24, Christian Di Lorenzo notifications@github.com
wrote:

Hey, thanks for being so prompt on my last issue… Unfortunately, I've got
another one.

When I hit this
linehttps://github.com/ChrisXu1221/CXAlertView/blob/master/CXAlertView/CXAlertView.m#L815in
@ChrisXu1221 https://github.com/ChrisXu1221's alert view, I get a bunch
of log warnings like this:

<Error>: CGContextRestoreGState: invalid context 0x0. This is a
serious error. This
application, or a library it uses, is using an invalid context  and is
thereby contributing
to an overall degradation of system stability and reliability. This
notice is a courtesy:
please fix this problem. It will become a fatal error in an upcoming update.

Other warnings simply substitute CGContextRestoreGState with other
functions such as CGContextAddRect and CGContextEndTransparencyLayer. I
think the root problem is an invalid context somehow.

Here's a link to a bunch of these log warnings:
https://gist.github.com/rcdilorenzo/6792876

—
Reply to this email directly or view it on
GitHubhttps://github.com/radi/LiveFrost/issues/6
.

**Comment by rcdilorenzo** [comment] 2013-10-02 12:32
- Latest commit radi/LiveFrost@472f86b5fb4cb51b76cf3f83f349b2db6707a78a
- Mac OS X 10.8.5
- iOS 7 - Official release

**Comment by evadne** [comment] 2013-10-02 12:54
Which device? Is it the simulator or a specific iOS device?

**Comment by rcdilorenzo** [comment] 2013-10-02 14:05
Simulator...

**Comment by evadne** [comment] 2013-10-02 14:08
Please test this on a real device. If you can reproduce the issue there, I’ll be happy to assist.

Best,
Eve

**Comment by ghost** [comment] 2013-10-02 14:57
Simulator or device, a test case would be nice. If you could assemble a sample project and upload that to Github, maybe attach a link to it to this ticket, it should be fairly easy to see if we have a problem, and be able to suss it out if we do.

That log doesn't tell us anything about how this is happening. A live patient would be more interesting to play with, it would certainly tell us _where_ the error is happening and possibly _why_.

We seem to have the one obvious case for corrupting a CGContext covered, that being to initialize one with a CGRect that's effectively CGRectZero. There may yet be other cases that we haven't covered.

**Comment by rcdilorenzo** [comment] 2013-10-02 14:58
Ok, it may be a little while before I can get to it, but I'll try to get that to you guys. Thanks for your help!

**Comment by ChrisXu** [comment] 2013-10-02 15:10
@rcdilorenzo Sorry for that I didn't notice the console. I am trying to figure out cause of this.

**Comment by ghost** [comment] 2013-10-02 16:35
I took a look at CXAlertView's Demo project and played with break pointers for a few minutes. The problem is that in this demo project, you're setting the LFGlassView when the view's own bounds are set to zero, because the CGRect that you're using to initialize this view (referenced by self.containerView.frame) is initially CGRectZero, or {0,0,0,0}.

The way LFGlassView works, it precalculates the blur kernel and preallocates bits like the CGContexts used for the blurring effect, the scaled size of the buffers we'd like to draw into, and other bits based on the LFGlassView's current bounds and positioning.

Now, this should be a condition that we bail out of nicely, like GLKViews do.

While some bits of our code return early and do nothing when there's no view big enough for it to render anything to, there's one method that doesn't. That's -refresh.

While it does check for the presence of the superview, it doesn't check that the ivar bufferSize is not CGRectZero up front, nor does it check that ivar effectInContext is not NULL. 

I'd like to fix this one right at the problem's root, rather than do an "is not null" bit at the beginning of -refresh. Pull request forthcoming...

**Comment by ghost** [comment] 2013-10-02 17:08
Issue followed up in pull request #7.

**Comment by rcdilorenzo** [comment] 2013-10-02 17:15
Thanks, just let me know when it gets merged so that I can integrate it back it my stuff.

**Comment by ghost** [comment] 2013-10-05 13:16
Okay @ChrisXu1221 . I've merged in the PR to the develop branch, so you can pull it off and test from there, if you'd like.

I've tried it against CXAlertViewDemo, and since yours diverges from this one a bit, you'll have sure -refresh looks like the following for your stuff and our stuff to play nice. And you can leave the blurSuperView ivar in the header file, that's fine as it is.

``` objective-c
- (void) refresh {
#ifdef DEBUG
    NSParameterAssert(self.superview);
    NSParameterAssert(_effectInContext);
    NSParameterAssert(_effectOutContext);
#endif
    if (!self.blurSuperView) {
        self.blurSuperView = self.superview;
    }

    CGContextRef effectInContext = _effectInContext;
    CGContextRef effectOutContext = _effectOutContext;
    vImage_Buffer effectInBuffer = _effectInBuffer;
    vImage_Buffer effectOutBuffer = _effectOutBuffer;

    self.hidden = YES;
    [self.blurSuperView.layer renderInContext:effectInContext];
    self.hidden = NO;

    uint32_t blurKernel = _precalculatedBlurKernel;

    vImageBoxConvolve_ARGB8888(&effectInBuffer, &effectOutBuffer, NULL, 0, 0, blurKernel, blurKernel, 0, kvImageEdgeExtend);
    vImageBoxConvolve_ARGB8888(&effectOutBuffer, &effectInBuffer, NULL, 0, 0, blurKernel, blurKernel, 0, kvImageEdgeExtend);
    vImageBoxConvolve_ARGB8888(&effectInBuffer, &effectOutBuffer, NULL, 0, 0, blurKernel, blurKernel, 0, kvImageEdgeExtend);

    CGImageRef outImage = CGBitmapContextCreateImage(effectOutContext);
    self.layer.contents = (__bridge id)(outImage);
    CGImageRelease(outImage);
}
```

@evadne is still working on a solution for rendering to arbitrary layers that are not the superview's, so I think this is the best way to get your fork and our stuff playing nicely. Let me know if you run into any trouble with it.

**Comment by ChrisXu** [comment] 2013-10-05 13:40
@nglevin Thanks, I will update it.

**Comment by ghost** [comment] 2013-11-20 02:57
Will close this issue when the master branch is updated.

**Closed as completed** 2013-11-20 04:44 UTC
